/*
 * Bachelor-Thesis
 * Performance Test for pdf generators
 *
 * OpenAPI spec version: 1.0.0
 * Contact: denisbittante@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ch.ffhs.dinf.osre.api.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModelProperty;

/**
 * Pdf
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-11-04T08:37:53.279Z")
public class Pdf   {
  @JsonProperty("data")
  private List<Row> data = null;

  /**
   * Test-Scenario definied which template the generator has to use
   */
  public enum ScenarioEnum {
    TESTSCENARIO1("testscenario1"),
    
    TESTSCENARIO2("testscenario2"),
    
    TESTSCENARIO3("testscenario3"),
    
    TESTSCENARIO4("testscenario4"),
    
    TESTSCENARIO5("testscenario5");

    private String value;

    ScenarioEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ScenarioEnum fromValue(String text) {
      for (ScenarioEnum b : ScenarioEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("scenario")
  private ScenarioEnum scenario = null;

  public Pdf data(List<Row> data) {
    this.data = data;
    return this;
  }

  public Pdf addDataItem(Row dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<Row>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Get data
   * @return data
   **/
  @JsonProperty("data")
  @ApiModelProperty(value = "")
  public List<Row> getData() {
    return data;
  }

  public void setData(List<Row> data) {
    this.data = data;
  }

  public Pdf scenario(ScenarioEnum scenario) {
    this.scenario = scenario;
    return this;
  }

  /**
   * Test-Scenario definied which template the generator has to use
   * @return scenario
   **/
  @JsonProperty("scenario")
  @ApiModelProperty(value = "Test-Scenario definied which template the generator has to use")
  public ScenarioEnum getScenario() {
    return scenario;
  }

  public void setScenario(ScenarioEnum scenario) {
    this.scenario = scenario;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pdf pdf = (Pdf) o;
    return Objects.equals(this.data, pdf.data) &&
        Objects.equals(this.scenario, pdf.scenario);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, scenario);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pdf {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    scenario: ").append(toIndentedString(scenario)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

