/*
 * Bachelor-Thesis
 * Performance Test for pdf generators
 *
 * OpenAPI spec version: 1.0.0
 * Contact: denisbittante@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.ffhs.dinf.osre.engine.api;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/**
 * Pdf
 */

public class PdfRequest {
	
	private ArrayList<HashMap<String, String>> data;
	
	public PdfRequest() {
	}
	public PdfRequest(ArrayList<HashMap<String, String>> data) {
		this.data = data;
	}

	public List<HashMap<String, String>> getData() {
		return data;
	}

	public void setData(ArrayList<HashMap<String, String>> data) {
		this.data = data;
	}

	@Override
	public String toString() {
		if (data == null || data.isEmpty()) {
			return "no data";

		} else {
			StringBuffer buffer = new StringBuffer();
			for (HashMap<String, String> hashMap : data) {

				for (String key : hashMap.keySet()) {
					buffer.append(key);
					buffer.append("\n");

				}
			}
			return buffer.toString();
		}

	}

}
