/*
 * Bachelor-Thesis
 * Performance Test for pdf generators
 *
 * OpenAPI spec version: 1.0.0
 * Contact: denisbittante@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.ffhs.dinf.osre.engine.api;

import java.util.ArrayList;

/**
 * Pdf
 */

public class PdfRequestScenario1 {

	private ArrayList<ActivityDetails> data;

	public PdfRequestScenario1() {
	}

	public ArrayList<ActivityDetails> getData() {
		return data;
	}

	public void setData(ArrayList<ActivityDetails> data) {
		this.data = data;
	}

}
